# Complete NumPy Tutorial (Basics to Advanced)

This notebook covers everything you need to know about NumPy, from fundamentals to advanced topics like linear algebra, broadcasting, masked arrays, FFT, file I/O, performance, and more.

## What is NumPy and Why It's Essential

NumPy (Numerical Python) is the fundamental package for numerical computing in Python. It provides:
- **Efficient arrays**: Multi-dimensional arrays (ndarrays) faster than Python lists
- **Mathematical functions**: Linear algebra, statistics, Fourier transforms
- **Broadcasting**: Perform operations on arrays of different shapes
- **Integration**: Works with pandas, matplotlib, scikit-learn
- **Performance**: Written in C, 50-100x faster than pure Python

## Installation

```bash
pip install numpy
```

Check installation:
```python
import numpy as np
print(np.__version__)
```

In [2]:
import numpy as np
np.random.seed(42)  # for reproducibility

## 1. Array Creation

### From Python lists/tuples

In [ ]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D:", arr_1d)

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D:\n", arr_2d)

# From tuple
arr_tuple = np.array((10, 20, 30))
print("From tuple:", arr_tuple)

### Using `arange`, `linspace`, `logspace`, `geomspace`

In [ ]:
print("arange(0, 10, 2):", np.arange(0, 10, 2))
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))
print("logspace(1, 3, 3):", np.logspace(1, 3, 3))  # 10^1 to 10^3
print("geomspace(1, 1000, 4):", np.geomspace(1, 1000, 4))

### Zeros, Ones, Empty, Full

In [ ]:
print("np.zeros((2,3)):\n", np.zeros((2,3)))
print("np.ones((3,3)):\n", np.ones((3,3)))
print("np.empty((2,2)) (uninitialized):\n", np.empty((2,2)))
print("np.full((2,2), 7):\n", np.full((2,2), 7))

### Identity and Diagonal Matrices

In [ ]:
print("np.eye(3):\n", np.eye(3))
print("np.identity(3):\n", np.identity(3))
print("np.diag([1,2,3]):\n", np.diag([1,2,3]))

### Random Arrays

In [ ]:
print("Uniform [0,1):", np.random.rand(3))
print("Standard normal:", np.random.randn(3))
print("Random integers [0,10):", np.random.randint(0, 10, 5))
print("Random sample:", np.random.random(4))

### `*_like` Functions

In [3]:
base = np.array([[1,2],[3,4]])
print("np.zeros_like(base):\n", np.zeros_like(base))
print("np.ones_like(base):\n", np.ones_like(base))
print("np.full_like(base, 9):\n", np.full_like(base, 9))

np.zeros_like(base):
 [[0 0]
 [0 0]]
np.ones_like(base):
 [[1 1]
 [1 1]]
np.full_like(base, 9):
 [[9 9]
 [9 9]]


### Grids: `meshgrid`, `mgrid`, `ogrid`

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
X, Y = np.meshgrid(x, y)
print("meshgrid X:\n", X)
print("meshgrid Y:\n", Y)

print("mgrid[0:3,0:3]:\n", np.mgrid[0:3, 0:3])
print("ogrid[0:3,0:3]:\n", np.ogrid[0:3, 0:3])

## 2. Array Attributes

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape:", arr.shape)   # (2,3)
print("dtype:", arr.dtype)   # int64
print("size:", arr.size)     # 6
print("ndim:", arr.ndim)     # 2
print("nbytes:", arr.nbytes) # total bytes

## 3. Data Types and Conversion

In [ ]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype(float)
print(arr_float, arr_float.dtype)

arr_str = arr_int.astype(str)
print(arr_str, arr_str.dtype)

## 4. Basic Array Operations (Element-wise)

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b:", a+b)
print("a*b:", a*b)
print("a/b:", a/b)
print("a**2:", a**2)
print("a > 2:", a > 2)

a+b: [5 7 9]
a*b: [ 4 10 18]
a/b: [0.25 0.4  0.5 ]
a**2: [1 4 9]
a > 2: [False False  True]


In [8]:
mask = a > 1

In [9]:
mask

array([False,  True,  True])

In [10]:
a[mask]

array([2, 3])

In [11]:
a[a>1]

array([2, 3])

## 5. Broadcasting

NumPy allows arithmetic between arrays of different shapes.

In [ ]:
# Scalar + array
arr = np.array([1,2,3])
print("arr + 10:", arr + 10)

# Vector + matrix (row broadcast)
mat = np.array([[1,2,3],[4,5,6]])
vec = np.array([10,20,30])
print("mat + vec:\n", mat + vec)

# Column vector broadcasting
col = np.array([[10],[20]])
print("mat + col:\n", mat + col)

# Advanced: using np.newaxis
row = np.array([1,2,3])[:, np.newaxis]  # shape (3,1)
col = np.array([4,5,6])[np.newaxis, :]  # shape (1,3)
print("row + col:\n", row + col)

## 6. Indexing and Slicing

In [ ]:
arr = np.arange(10)
print("arr[2:7:2]:", arr[2:7:2])
print("arr[-3:]:", arr[-3:])

mat = np.arange(9).reshape(3,3)
print("mat[1,2]:", mat[1,2])
print("mat[:2, 1:]:\n", mat[:2, 1:])
print("mat[::2, ::2]:\n", mat[::2, ::2])

## 7. Boolean Indexing (Masking)

In [ ]:
arr = np.array([1,2,3,4,5])
mask = arr > 2
print("Mask:", mask)
print("arr[mask]:", arr[mask])
print("Even numbers:", arr[arr % 2 == 0])

# Modify with mask
arr[arr > 3] = 99
print("After modification:", arr)

## 8. Fancy Indexing

In [ ]:
arr = np.array([10,20,30,40,50])
indices = [0,2,4]
print("arr[indices]:", arr[indices])

mat = np.arange(12).reshape(3,4)
rows = np.array([0,2])
cols = np.array([1,3])
print("mat[rows, cols]:", mat[rows, cols])  # (0,1) and (2,3)

# Outer indexing with ix_
print("mat[np.ix_(rows, cols)]:\n", mat[np.ix_(rows, cols)])

## 9. np.where() – Conditional Selection

In [ ]:
arr = np.array([1,2,3,4,5])
result = np.where(arr > 3, "high", "low")
print("Conditional:", result)

indices = np.where(arr > 3)
print("Indices where >3:", indices)

## 10. Set Operations

In [ ]:
a = np.array([1,2,3,2,4])
b = np.array([3,4,5,6])
print("Unique a:", np.unique(a))
print("Intersection:", np.intersect1d(a,b))
print("Union:", np.union1d(a,b))
print("Difference (a-b):", np.setdiff1d(a,b))
print("Is element in b?", np.in1d(a,b))

## 11. Logical Operations

In [ ]:
a = np.array([True, False, True])
b = np.array([False, False, True])
print("logical_and:", np.logical_and(a,b))
print("logical_or:", np.logical_or(a,b))
print("logical_not:", np.logical_not(a))
print("all(a):", np.all(a))
print("any(a):", np.any(a))

## 12. String Operations (`np.char`)

In [ ]:
names = np.array(["alice", "BOB", "Charlie"])
print("Upper:", np.char.upper(names))
print("Length:", np.char.str_len(names))
print("Replace 'a' with 'X':", np.char.replace(names, 'a', 'X'))

sentence = np.array(["one two three", "four five six"])
print("Split:", np.char.split(sentence))

## 13. Mathematical Functions

In [ ]:
x = np.linspace(0, np.pi, 4)
print("sin:", np.sin(x))
print("exp:", np.exp(x))
print("log:", np.log(x))
print("sqrt:", np.sqrt(x))

## 14. Aggregations (sum, mean, min, max, etc.)

In [ ]:
arr = np.array([[1,2],[3,4]])
print("Sum:", arr.sum())
print("Sum axis=0 (columns):", arr.sum(axis=0))
print("Mean:", arr.mean())
print("Min:", arr.min())
print("Cumulative sum:", arr.cumsum())

## 15. Statistical Functions

In [ ]:
data = np.array([10,12,23,23,16,23,21,16])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std:", np.std(data))
print("Variance:", np.var(data))
print("Percentile 90:", np.percentile(data, 90))

# Correlation
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])
print("Correlation matrix:\n", np.corrcoef(x,y))

# Histogram
hist, edges = np.histogram(data, bins=5)
print("Histogram:", hist)

## 16. Sorting and Searching

In [ ]:
arr = np.array([3,1,2,5,4])
print("Sorted copy:", np.sort(arr))
arr.sort()
print("In-place sorted:", arr)

# argsort
arr2 = np.array([40,10,30,20])
indices = np.argsort(arr2)
print("Indices:", indices)
print("arr2[indices]:", arr2[indices])

# searchsorted (array must be sorted)
sorted_arr = np.array([1,3,5,7,9])
print("Insertion positions for [2,5,10]:", np.searchsorted(sorted_arr, [2,5,10]))

# lexsort (sort by multiple keys)
last = np.array(['Smith','Jones','Smith','Adams'])
first = np.array(['John','Bob','Alice','Tom'])
ind = np.lexsort((first, last))
print("Sorted by last, then first:", list(zip(last[ind], first[ind])))

# partition (partial sort)
arr3 = np.array([7,2,5,1,9,3])
print("Partition (k=3):", np.partition(arr3, 3))

## 17. Array Manipulation (reshape, resize, flatten, ravel, transpose)

In [ ]:
arr = np.arange(12)
print("reshape(3,4):\n", arr.reshape(3,4))
print("reshape(2,-1):\n", arr.reshape(2,-1))

# resize (modifies original)
a = np.array([1,2,3,4])
a.resize(2,3)
print("resize:\n", a)

# flatten vs ravel
mat = np.array([[1,2],[3,4]])
print("flatten (copy):", mat.flatten())
print("ravel (view):", mat.ravel())

# transpose
print("transpose:\n", mat.T)

## 18. Advanced: Linear Algebra (`np.linalg`)

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Dot product:\n", np.dot(A, B))
print("Matrix multiplication (@):\n", A @ B)
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Eigenvalues:", np.linalg.eigvals(A))

# Solve linear system Ax = b
A = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(A, b)
print("Solution x:", x)
print("Check A @ x:", A @ x)

# SVD
U, s, Vt = np.linalg.svd(A)
print("SVD singular values:", s)

# Norms
print("Frobenius norm:", np.linalg.norm(A))

## 19. Advanced Broadcasting

We already covered basics; here are more tricks: `np.newaxis`, `np.broadcast_to`, and rules.

In [ ]:
# Using np.newaxis to add dimensions
row = np.array([1,2,3])[:, np.newaxis]   # shape (3,1)
col = np.array([4,5,6])[np.newaxis, :]   # shape (1,3)
print("row + col =\n", row + col)

# Explicit broadcasting
arr = np.arange(4).reshape(2,2)
broadcasted = np.broadcast_to(arr, (3,2,2))
print("broadcast_to shape:", broadcasted.shape)

# Broadcasting rules: trailing dimensions must match or be 1

## 20. Structured Arrays (Record Arrays)

Store mixed data types in one array.

In [ ]:
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f8')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 75.2)], dtype=dtype)
print("Structured array:\n", data)
print("Names:", data['name'])
print("Ages:", data['age'])

# Access by field
data['age'][0] = 26
print("Modified age:", data['age'])

## 21. Masked Arrays (`np.ma`)

Handle missing or invalid data.

In [ ]:
import numpy.ma as ma

x = ma.array([1, 2, -999, 4], mask=[0,0,1,0])
print("Masked array:", x)
print("Mean ignoring mask:", x.mean())

# Mask based on condition
y = ma.masked_where(y < 0, y)  # common pattern

## 22. Fourier Transforms (`np.fft`)

In [ ]:
# Example: 5 Hz sine wave
fs = 1000  # sampling frequency
t = np.linspace(0, 1, fs)
signal = np.sin(2 * np.pi * 5 * t)

# FFT
spectrum = np.fft.fft(signal)
freqs = np.fft.fftfreq(len(signal), 1/fs)

print("FFT shape:", spectrum.shape)
print("Positive frequencies up to Nyquist:", freqs[:5])

# Inverse FFT
reconstructed = np.fft.ifft(spectrum)
print("Reconstruction error:", np.max(np.abs(reconstructed - signal)))

## 23. File I/O – Save and Load Arrays

In [ ]:
# Binary .npy (single array)
arr = np.array([1,2,3])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print("Loaded from .npy:", loaded)

# Multiple arrays in .npz
np.savez('multiple.npz', a=arr, b=np.array([4,5,6]))
data = np.load('multiple.npz')
print("From .npz:", data['a'], data['b'])

# Text files
np.savetxt('data.txt', arr, delimiter=',')
txt_loaded = np.loadtxt('data.txt', delimiter=',')
print("From txt:", txt_loaded)

# Clean up (optional)
import os
for f in ['my_array.npy', 'multiple.npz', 'data.txt']:
    if os.path.exists(f): os.remove(f)

## 24. Performance and Memory Efficiency

- Use in‑place operations: `arr += 1` instead of `arr = arr + 1`
- Reuse memory with `out` parameter
- Use `np.memmap` for large datasets
- Avoid unnecessary copies (views vs copies)

In [ ]:
# In-place vs copy
arr = np.arange(10_000_000)
# arr = arr + 1  (creates new array)
arr += 1          # modifies in-place, faster

# Using out parameter
a = np.array([1,2,3])
b = np.array([4,5,6])
result = np.empty(3)
np.add(a, b, out=result)  # no new allocation
print("out result:", result)

# Views vs copies
original = np.array([1,2,3,4,5])
view = original[1:4]      # view (no copy)
copy = original[1:4].copy() # explicit copy
view[0] = 999
print("Original after view modification:", original)  # changed

# memmap example (commented, but concept)
# fp = np.memmap('large.dat', dtype='float32', mode='w+', shape=(1000000, 1000))

## 25. Axis Manipulation (moveaxis, rollaxis, expand_dims, squeeze)

In [ ]:
arr = np.arange(24).reshape(2,3,4)
print("Original shape:", arr.shape)

# Move axis (move axis 0 to position 2)
moved = np.moveaxis(arr, 0, 2)
print("After moveaxis (0->2):", moved.shape)

# Expand dimensions
expanded = np.expand_dims(arr, axis=1)
print("Expand_dims (axis=1):", expanded.shape)

# Squeeze (remove size-1 dimensions)
arr_squeeze = np.array([[[1,2,3]]])  # shape (1,1,3)
print("Squeezed shape:", np.squeeze(arr_squeeze).shape)

## 26. Polynomials (`np.polyfit`, `np.poly1d`)

In [ ]:
# Generate noisy data
x = np.linspace(0, 5, 50)
y = 2*x**2 - 3*x + 1 + np.random.randn(50)*5

# Fit polynomial of degree 2
coeffs = np.polyfit(x, y, 2)
print("Coefficients (a, b, c):", coeffs)

# Create callable polynomial
p = np.poly1d(coeffs)
print("Polynomial:", p)
print("p(2):", p(2))

# Evaluate at points
y_fit = p(x)

## 27. Advanced Indexing Tricks

- Ellipsis (`...`)
- Combining boolean and fancy indexing
- `np.ix_` for outer indexing (seen earlier)

In [ ]:
# Ellipsis
arr = np.arange(24).reshape(2,3,4)
print("arr[..., 0] (last axis first element):\n", arr[..., 0])
print("arr[0, ...] (first row, all others):\n", arr[0, ...])

# Combine boolean and fancy
mat = np.random.rand(5,5)
row_mask = mat[:,0] > 0.5
col_indices = [0,2,4]
result = mat[row_mask][:, col_indices]  # works
print("Combined indexing shape:", result.shape)

## Summary

You have now covered:
- Basics: creation, attributes, dtype, operations
- Indexing & slicing (basic, boolean, fancy, `where`)
- Set and logical operations
- String operations
- Mathematics, aggregations, statistics
- Sorting, searching, manipulation
- Advanced: linear algebra, broadcasting, structured arrays, masked arrays, FFT, file I/O, performance, axis manipulation, polynomials, advanced indexing

NumPy is the foundation of scientific computing in Python. Master these tools to handle any numerical task efficiently.