# The Ultimate NumPy Tutorial (Basics → Advanced)

This notebook contains **everything** you need to master NumPy:
- Array creation from lists, tuples, iterables, ranges, and random distributions
- Array attributes, data types, and type conversion
- Indexing, slicing, boolean masking, fancy indexing, and `np.where()`
- Set operations, logical operations, and vectorized string methods
- Mathematical functions, aggregations, and descriptive statistics
- Sorting, searching, and partial sorting (`partition`)
- Array manipulation: reshape, resize, flatten, ravel, transpose
- **Advanced topics**:
  - Linear algebra (`np.linalg`)
  - Broadcasting (including `np.newaxis` and `np.broadcast_to`)
  - Structured arrays (mixed data types)
  - Masked arrays (`np.ma`)
  - Fourier transforms (`np.fft`)
  - File I/O (binary and text)
  - Performance optimization (in‑place ops, `out` parameter, views vs copies)
  - Axis manipulation (`moveaxis`, `expand_dims`, `squeeze`)
  - Polynomials (`polyfit`, `poly1d`)
  - Advanced indexing (ellipsis, combined boolean/fancy)

All examples are self‑contained and runnable.

In [1]:
import numpy as np
import numpy.ma as ma

# Set seed for reproducibility
np.random.seed(42)

## 1. Array Creation – All Methods

### From Python sequences (list, tuple)

In [ ]:
# From list
a = np.array([1, 2, 3])
print("From list:", a)

# From tuple
b = np.array((4, 5, 6))
print("From tuple:", b)

In [ ]:
print(np.array([1,1.2,12]))

In [ ]:
# From any iterable (e.g., generator)
d = np.fromiter(range(5), dtype=float)
print("From iterable:", d)

### Ranges: `arange`, `linspace`, `logspace`, `geomspace`

In [ ]:
np.logspace?

In [ ]:
np.logspace(start = 1,stop = 3,num = 10 ,base = 2)

In [ ]:
np.geomspace?

In [ ]:
print("arange(5, 10):", np.arange(5, 10))
print("arange(0, 10, 2):", np.arange(0, 10, 2))
print("linspace(1, 10, 5):", np.linspace(1, 10, 5))
print("linspace(0, 1, 5, endpoint=False):", np.linspace(0, 1, 5, endpoint=False))
print("logspace(1, 3, 3):", np.logspace(1, 3, 3))   # 10^1, 10^2, 10^3
print("geomspace(1, 1000, 4):", np.geomspace(1, 1000, 5))

### Zeros, Ones, Empty, Full

In [ ]:
print("np.zeros(3):", np.zeros(3))
print("np.zeros((3,4)):\n", np.zeros((3,4)))
print("np.ones((2,3)):\n", np.ones((2,3)))
print("np.empty((2,2)) (uninitialised, may be garbage):\n", np.empty((2,2)))
print("np.full((2,2), 7):\n", np.full((2,2), 7))

In [ ]:
np.ones((2, 3)) * 7

### Identity / Diagonal matrices

In [ ]:
np.identity?

In [ ]:
np.eye?

In [ ]:
print("np.eye(3):\n", np.eye(3,6,k=2))
print("np.eye(3, k=1):\n", np.eye(3, k=1))
print("np.eye(3, k=-1):\n", np.eye(3, k=-1))
print("np.identity(3):\n", np.identity(3))
print("np.diag([1,2,3]):\n", np.diag([1,2,3]))

### Random arrays

In [ ]:
np.random.randint?

In [ ]:
# Set seed for reproducibility
np.random.seed(0)
print("Uniform [0,1):", np.random.rand(30000))
print("Standard normal:", np.random.randn(30))
print("Random integers 0-9:", np.random.randint(5, size=5))
print("Random integers 5-10, shape (2,3):\n", np.random.randint(5, 10, (2,3)))
print("Random sample (0,1):", np.random.random(4))

In [ ]:
# Random choice from an array
choices = np.array([10, 20, 30, 50])
print("Random choice:", np.random.choice(choices))
print("5 choices with replacement:", np.random.choice(choices, 10))

In [ ]:
# Shuffle in-place
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("After shuffle:", arr)

In [ ]:
# Random choice from an array
choices = np.array([10, 20, 30, 40])
print("Random choice:", np.random.choice(choices))
print("5 choices with replacement:", np.random.choice(choices, 5))

# Shuffle in-place
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("After shuffle:", arr)

# Setting seed for reproducibility
np.random.seed(0)
print("Reproducible random:", np.random.rand(3))

### `*_like` functions

In [ ]:
base = np.array([[1, 2], [3, 4]])
print("np.zeros_like(base):\n", np.zeros_like(base))
print("np.ones_like(base):\n", np.ones_like(base))
print("np.full_like(base, 9):\n", np.full_like(base, 9))

### Grids: `meshgrid`, `mgrid`, `ogrid`

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
X, Y = np.meshgrid(x, y)
print("meshgrid X:\n", X)
print("meshgrid Y:\n", Y)

print("mgrid[0:3,0:3]:\n", np.mgrid[0:3, 0:3])
print("ogrid[0:3,0:3]:\n", np.ogrid[0:3, 0:3])

### Minimum number of dimensions (`ndmin`)

In [ ]:
arr = arr.flatten()

In [ ]:
arr[1] = -5

In [ ]:
arr = arr.astype(np.uint8)

In [ ]:
arr.dtype

In [ ]:
arr = np.array([1, 2], dtype=float, ndmin=5)
print("Shape with ndmin=5:", arr.shape)   # (1,1,1,1,2)
print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)   # size * itemsize   

print(arr.astype(int))
print(arr.dtype)# Convert to int
print(arr.astype(str)) 
print(arr.dtype)# Convert to string

## 2. Array Attributes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape:", arr.shape)
print("dtype:", arr.dtype)
print("size:", arr.size)
print("ndim:", arr.ndim)
print("itemsize (bytes per element):", arr.itemsize)
print("nbytes (total memory):", arr.nbytes)

## 3. Data Types and Conversion

In [ ]:
arr_int = np.array([1, 2, 3])
arr_float = arr_int.astype(float)
arr_str = arr_int.astype(str)
print("int → float:", arr_float, arr_float.dtype)
print("int → str:", arr_str, arr_str.dtype)

# Truncation when converting float to int
arr_float2 = np.array([1.9, 2.5, 3.1])
print("float → int (truncates):", arr_float2.astype(int))

## 4. Basic Element‑wise Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b =", a + b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a ** 2 =", a ** 2)
print("a > 2 =", a > 2)

## 5. Indexing & Slicing (1D, 2D, 3D)

In [ ]:
arr1 = np.arange(10)
print("arr1[2:7:2] =", arr1[2:7:2])
print("arr1[-3:] =", arr1[-3:])

In [ ]:
mat = np.arange(9).reshape(3, 3)
print("mat:\n", mat)
print("mat[1, 2] =", mat[1, 2])
print("mat[1, :] =", mat[1, :])
print("mat[:, 1] =", mat[:, 1])
print("mat[:2, 1:] =\n", mat[:2, 1:])
print("mat[::2, ::2] =\n", mat[::2, ::2])

In [ ]:
cube = np.arange(24).reshape(2, 3, 4)
print("cube:", cube)
print("cube[0, 1, 2] =", cube[0, 1, 2])
print("cube[1, :, :] (second block):\n", cube[1, :, :])
print("cube[..., 0] (last axis, first element):\n", cube[..., 0]) # In NumPy, ... (ellipsis) means "all preceding dimensions".
print("cube[1,...] =", cube[ 1,...])
print("cube[0, 1,...] =", cube[0, 1,...])
print("cube[0, 1, :] =", cube[0, 1, :])
print("cube[1, 1, 0:3:2] =", cube[1, 1, 0:3:2])

## 6. Boolean Indexing (Masking)

In [2]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 2
print("mask:", mask)
print("arr[mask]:", arr[mask])
print("arr[arr % 2 == 0]:", arr[arr % 2 == 0])

# Modify using mask
arr[arr > 3] = 99
print("After modification:", arr)
arr[0] = 500
print("After modifying first element:", arr)

mask: [False False  True  True  True]
arr[mask]: [3 4 5]
arr[arr % 2 == 0]: [2 4]
After modification: [ 1  2  3 99 99]
After modifying first element: [500   2   3  99  99]


## 7. Fancy Indexing

In [3]:
arr = np.array([10, 20, 30, 40, 50])
indices = [3, 0, 2]
print("arr[indices]:", arr[indices])

mat = np.arange(12).reshape(3, 4)
rows = [0, 2]
cols = [1, 3]
print("mat[rows, cols]:", mat[rows, cols])   # (0,1) and (2,3)

# Outer indexing (block)
print("mat[np.ix_(rows, cols)]:\n", mat[np.ix_(rows, cols)])

arr[indices]: [40 10 30]
mat[rows, cols]: [ 1 11]
mat[np.ix_(rows, cols)]:
 [[ 1  3]
 [ 9 11]]


## 8. `np.where()` – Conditional Selection

In [4]:
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 3, "high", "low")
print("where condition:", result)

# Get indices where condition is True
indices = np.where(arr > 3)
print("Indices of >3:", indices)

where condition: ['low' 'low' 'low' 'high' 'high']
Indices of >3: (array([3, 4]),)


## 9. Set Operations

In [5]:
a = np.array([1, 2, 3, 2, 4])
b = np.array([3, 4, 5, 6])
print("Unique a:", np.unique(a))
print("Intersection:", np.intersect1d(a, b))
print("Union:", np.union1d(a, b))
print("Difference (a - b):", np.setdiff1d(a, b))
print("Difference (b - a):", np.setdiff1d(b, a))
print("Elements of a in b?", np.isin(a, b))
print("Elements of b in a?", np.isin(b, a))

Unique a: [1 2 3 4]
Intersection: [3 4]
Union: [1 2 3 4 5 6]
Difference (a - b): [1 2]
Difference (b - a): [5 6]
Elements of a in b? [False False  True False  True]
Elements of b in a? [ True  True False False]


## 10. Logical Operations

In [6]:
p = np.array([True, False, True])
q = np.array([False, False, True])
print("logical_and:", np.logical_and(p, q))
print("logical_or:", np.logical_or(p, q))
print("logical_not:", np.logical_not(p))
print("all(p):", np.all(p))
print("any(p):", np.any(p))

logical_and: [False False  True]
logical_or: [ True False  True]
logical_not: [False  True False]
all(p): False
any(p): True


## 11. Vectorized String Operations (`np.char`)

In [9]:
names = np.array(["alice", "BOB", "Charlie"])
print("Upper:", np.char.upper(names))
print("Lower:", np.char.lower(names))
print("Length:", np.char.str_len(names))
print("Replace 'a' with 'X':", np.char.replace(names, 'a', 'X'))

sentence = np.array(["one two three", "four five six"])
print("Split:", np.char.split(sentence,maxsplit =1))

Upper: ['ALICE' 'BOB' 'CHARLIE']
Lower: ['alice' 'bob' 'charlie']
Length: [5 3 7]
Replace 'a' with 'X': ['Xlice' 'BOB' 'ChXrlie']
Split: [list(['one', 'two three']) list(['four', 'five six'])]


## 12. Mathematical Functions (ufuncs)

In [10]:
x = np.linspace(1, np.pi, 4)
print("x =", x)
print("sin(x) =", np.sin(x))
print("exp(x) =", np.exp(x))
print("log(x) =", np.log(x))
print("sqrt(x) =", np.sqrt(x))

x = [1.         1.71386422 2.42772844 3.14159265]
sin(x) = [8.41470985e-01 9.89783234e-01 6.54759373e-01 1.22464680e-16]
exp(x) = [ 2.71828183  5.55036792 11.33310893 23.14069263]
log(x) = [0.         0.5387506  0.88695602 1.14472989]
sqrt(x) = [1.         1.30914637 1.55811695 1.77245385]


## 13. Aggregations (sum, mean, min, max, cumsum, etc.)

In [11]:
mat = np.array([[1, 2], [3, 4]])
print(mat)
print("Sum:", mat.sum())
print("Sum axis=0 (columns):", mat.sum(axis=0))
print("Sum axis=1 (rows):", mat.sum(axis=1))
print("Mean:", mat.mean())
print("Min:", mat.min())
print("Max:", mat.max())
print("Argmin (flattened):", mat.argmin())
print("Cumulative sum:", mat.cumsum())
print("Cumulative product:", mat.cumprod())

[[1 2]
 [3 4]]
Sum: 10
Sum axis=0 (columns): [4 6]
Sum axis=1 (rows): [3 7]
Mean: 2.5
Min: 1
Max: 4
Argmin (flattened): 0
Cumulative sum: [ 1  3  6 10]
Cumulative product: [ 1  2  6 24]


## 14. Statistical Functions

In [ ]:
data = np.array([10, 12, 23, 23, 16, 23, 21, 16])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std:", np.std(data))
print("Variance:", np.var(data))
print("90th percentile:", np.percentile(data, 90))

# Mode via unique
vals, counts = np.unique(data, return_counts=True)
mode = vals[np.argmax(counts)]
print("Mode:", mode)

# Correlation
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])
print("Correlation matrix:\n", np.corrcoef(x, y))

# Histogram
hist, edges = np.histogram(data, bins=5)
print("Histogram counts:", hist)

In [12]:
np.sort?

Signature:      
np.sort(
    a,
    axis=-1,
    kind=None,
    order=None,
    *,
    stable=None,
    descending=<no value>,
)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x000001B57FEEC7C0>
File:            c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and,
    in general, the actual implementation will vary with data type.
    The 'mergesort' option is retained for backwards compat

## 15. Sorting and Searching

In [ ]:
arr = np.array([3, 1, 2, 5, 4])
print("np.sort(arr):", np.sort(arr))        # copy
arr.sort()
print("arr.sort() in-place:", arr)

# argsort
arr2 = np.array([40, 10, 30, 20])
idx = np.argsort(arr2)
print("argsort indices:", idx)
print("arr2[idx]:", arr2[idx])

# searchsorted (array must be sorted)
sorted_arr = np.array([1, 3, 5, 7, 9])
print("Insert positions for [2,5,10]:", np.searchsorted(sorted_arr, [2, 5, 10]))

# lexsort (multiple keys)
last = np.array(['Smith', 'Jones', 'Smith', 'Adams'])
first = np.array(['John', 'Bob', 'Alice', 'Tom'])
ind = np.lexsort((first, last))
print("Sorted by last, then first:", list(zip(last[ind], first[ind])))

# partition (partial sort – first k smallest)
arr3 = np.array([7, 2, 5, 1, 9, 3])
print("Partition (k=3):", np.partition(arr3, 3))

## 16. Array Manipulation (reshape, resize, flatten, ravel, transpose)

In [13]:
arr = np.arange(12)
print("reshape(3,4):\n", arr.reshape(3, 4))
print("reshape(2, -1):\n", arr.reshape(2, -1))

# resize (in-place, can change size)
a = np.array([1, 2, 3, 4])
a.resize(2, 3)   # fills with zeros if larger
print("a.resize(2,3):\n", a)

# np.resize (returns new array, repeats)
b = np.array([1, 2, 3])
c = np.resize(b, (2, 4))
print("np.resize (repeats):\n", c)

# flatten vs ravel
mat = np.array([[1, 2], [3, 4]])
print("flatten (copy):", mat.flatten())
print("ravel (view):", mat.ravel())

# transpose
print("mat.T:\n", mat.T)
print("transpose(1,0):\n", mat.transpose(1, 0))

reshape(3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(2, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
a.resize(2,3):
 [[1 2 3]
 [4 0 0]]
np.resize (repeats):
 [[1 2 3 1]
 [2 3 1 2]]
flatten (copy): [1 2 3 4]
ravel (view): [1 2 3 4]
mat.T:
 [[1 3]
 [2 4]]
transpose(1,0):
 [[1 3]
 [2 4]]


## 17. Linear Algebra (`np.linalg`)

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A @ B (matrix multiplication):\n", A @ B)
print("np.linalg.inv(A):\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Eigenvalues:", np.linalg.eigvals(A))

# Solve linear system
A2 = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A2, b)
print("Solution x:", x)
print("Check A2 @ x:", A2 @ x)

# SVD
U, s, Vt = np.linalg.svd(A2)
print("Singular values:", s)

A @ B (matrix multiplication):
 [[19 22]
 [43 50]]
np.linalg.inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132+0.j  5.37228132+0.j]
Solution x: [2. 3.]
Check A2 @ x: [9. 8.]
Singular values: [3.61803399 1.38196601]


## 18. Advanced Broadcasting (with `newaxis`, `broadcast_to`)

In [15]:
# Using np.newaxis to add dimensions
row = np.array([1, 2, 3])[:, np.newaxis]   # shape (3,1)
col = np.array([4, 5, 6])[np.newaxis, :]   # shape (1,3)
print(row)
print(col)
print("row + col:\n", row + col)

# Explicit broadcasting
arr = np.arange(4).reshape(2, 2)
broadcasted = np.broadcast_to(arr, (3, 2, 2))
print("broadcast_to shape:", broadcasted.shape)
print(broadcasted)

[[1]
 [2]
 [3]]
[[4 5 6]]
row + col:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]
broadcast_to shape: (3, 2, 2)
[[[0 1]
  [2 3]]

 [[0 1]
  [2 3]]

 [[0 1]
  [2 3]]]


## 19. Structured Arrays (Record Arrays)

In [ ]:
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f8')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 75.2)], dtype=dtype)
print("Structured array:\n", data)
print("Names:", data['name'])
print("Ages:", data['age'])

# Modify a field
data['age'][0] = 26
print("Modified ages:", data['age'])

## 20. Masked Arrays (`np.ma`) – Handle Missing Data

In [ ]:
x = ma.array([1, 2, -999, 4], mask=[0, 0, 1, 0])
print("Masked array:", x)
print("Mean ignoring mask:", x.mean())

# Mask values that are negative
y = np.array([1, -5, 3, -2])
y_masked = ma.masked_where(y < 0, y)
print("Masked negative values:", y_masked)

In [ ]:
x= np.array([1,2,np.nan,4])

In [ ]:
ma.masked_where(np.isnan(x),x).mean()

## 21. Fourier Transforms (`np.fft`)

In [ ]:
# 5 Hz sine wave
fs = 1000
t = np.linspace(0, 1, fs)
signal = np.sin(2 * np.pi * 5 * t)

# FFT
spectrum = np.fft.fft(signal)
freqs = np.fft.fftfreq(len(signal), 1/fs)
print("FFT shape:", spectrum.shape)
print("First 5 positive frequencies:", freqs[:5])

# Inverse FFT (reconstruction)
reconstructed = np.fft.ifft(spectrum)
error = np.max(np.abs(reconstructed - signal))
print("Reconstruction error:", error)

## 22. File I/O (Save & Load)

In [ ]:
# Binary .npy (single array)
arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print(".npy load:", loaded)

In [ ]:
# Binary .npy (single array)
arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print(".npy load:", loaded)

# Multiple arrays in .npz
np.savez('multiple.npz', a=arr, b=np.array([4, 5, 6]))
data = np.load('multiple.npz')
print(".npz:", data['a'], data['b'])

# Text files
np.savetxt('data.txt', arr, delimiter=',')
txt_load = np.loadtxt('data.txt', delimiter=',')
print("Text load:", txt_load)

# Cleanup
import os
for f in ['my_array.npy', 'multiple.npz', 'data.txt']:
    if os.path.exists(f):
        os.remove(f)

## 23. Performance & Memory Efficiency

In [ ]:
# In-place operations (avoid copies)
arr = np.arange(1_000_000)
arr += 1   # faster than arr = arr + 1

# Using `out` parameter to reuse memory
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.empty(3)
np.add(a, b, out=result)
print("out result:", result)

# Views vs copies – views share memory
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]          # view
copy = original[1:4].copy()   # explicit copy
view[0] = 999
print("Original after view modification:", original)  # changed

# memmap (for arrays larger than RAM) – commented
# fp = np.memmap('large.dat', dtype='float32', mode='w+', shape=(10000, 1000))

## 24. Axis Manipulation (moveaxis, expand_dims, squeeze)

In [ ]:
arr = np.arange(24).reshape(2, 3, 4)
print("Original shape:", arr.shape)

moved = np.moveaxis(arr, 0, 2)
print("After moveaxis(0→2):", moved.shape)

expanded = np.expand_dims(arr, axis=1)
print("After expand_dims(axis=1):", expanded.shape)

squeezable = np.array([[[1, 2, 3]]])   # shape (1,1,3)
print("Squeezed shape:", np.squeeze(squeezable).shape)

## 25. Polynomials (`np.polyfit`, `np.poly1d`)

In [ ]:
# Generate noisy quadratic data
x = np.linspace(0, 5, 50)
y = 2*x**2 - 3*x + 1 + np.random.randn(50)*5

# Fit degree 2 polynomial
coeffs = np.polyfit(x, y, 2)
print("Fitted coefficients (a, b, c):", coeffs)

# Create callable polynomial
p = np.poly1d(coeffs)
print("Polynomial:", p)
print("p(2):", p(2))

## 26. Advanced Indexing Tricks (Ellipsis, Combined Boolean/Fancy)

In [ ]:
# Ellipsis (...)
arr = np.arange(24).reshape(2, 3, 4)
print("arr[..., 0] (last axis first element):\n", arr[..., 0])
print("arr[0, ...] (first block):\n", arr[0, ...])

# Combine boolean mask with fancy indexing
mat = np.random.rand(5, 5)
row_mask = mat[:, 0] > 0.5
col_indices = [0, 2, 4]
result = mat[row_mask][:, col_indices]
print("Combined indexing shape:", result.shape)

## 27. Copy vs View – Detailed

In [16]:
# .copy() creates a new independent array
original = np.array([1, 2, 3, 4])
copied = original.copy()
copied[0] = 999
print("Original after copy change:", original)   # unchanged

# .view() creates a new array that shares data
viewed = original.view()
viewed[0] = 888
print("Original after view change:", original)    # changed

# Slicing returns a view
slice_view = original[1:3]
slice_view[0] = 777
print("Original after slice view change:", original)

# Check memory sharing
print("original and copied share?", np.shares_memory(original, copied))
print("original and view share?", np.shares_memory(original, viewed))

Original after copy change: [1 2 3 4]
Original after view change: [888   2   3   4]
Original after slice view change: [888 777   3   4]
original and copied share? False
original and view share? True


## Summary

You have now mastered:
- **Creation** from sequences, ranges, random, grids, etc.
- **Attributes** and **dtype** conversion
- **Indexing** (basic, slice, boolean, fancy, `where`)
- **Set** and **logical** operations
- **String** vectorization with `np.char`
- **Math**, **aggregations**, **statistics**
- **Sorting** and **searching**
- **Manipulation** (reshape, resize, flatten, ravel, transpose)
- **Linear algebra** (inverse, determinant, eigenvalues, SVD, solving systems)
- **Broadcasting** (including `newaxis` and `broadcast_to`)
- **Structured arrays** (mixed types)
- **Masked arrays** (missing data)
- **Fourier transforms**
- **File I/O** (binary and text)
- **Performance** (in‑place, `out`, views vs copies)
- **Axis manipulation** (`moveaxis`, `expand_dims`, `squeeze`)
- **Polynomials**
- **Advanced indexing** (ellipsis, combined)

NumPy is the bedrock of scientific computing in Python. With this knowledge you are ready for data science, machine learning, engineering, and signal processing.