In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [10]:
arr1 = np.array([1,2,3,'4',5,6],dtype=int)

In [11]:
arr1

array([1, 2, 3, 4, 5, 6])

In [8]:
print(arr1)

['1' '2' '3' 'sdf' '5' '6']


In [12]:
arr1.dtype

dtype('int32')

In [13]:
arr1.size

6

In [14]:
arr1.shape

(6,)

In [15]:
arr1.ndim

1

In [16]:
arr1.itemsize

4

In [17]:
arr1.nbytes

24

In [19]:
arr1.dump("arr1.npy")

In [20]:
del arr1

In [21]:
arr1

NameError: name 'arr1' is not defined

In [23]:
arr1 = np.load("arr1.npy",allow_pickle=True)

In [24]:
arr1

array([1, 2, 3, 4, 5, 6])

In [25]:
import pickle

In [26]:
list1 = [1,2,3,4,5,6]

In [27]:
pickle.dump(list1,open("list1.pkl","wb"))

In [28]:
del list1

In [29]:
list1

NameError: name 'list1' is not defined

In [30]:
list1 = pickle.load(open("list1.pkl","rb"))

In [31]:
list1

[1, 2, 3, 4, 5, 6]

In [33]:
arr1

array([1, 2, 3, 4, 5, 6])

In [34]:
arr1[2]

3

In [35]:
arr1[2]=56

In [36]:
arr1

array([ 1,  2, 56,  4,  5,  6])

In [37]:
del arr1[2]

ValueError: cannot delete array elements

In [38]:
arr1[0:3]

array([ 1,  2, 56])

In [41]:
arr1[0:3] =[1,2]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [45]:
print(arr1.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [46]:
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1[0] = 'sdf'

In [ ]:
arr1[0] = '123'

In [ ]:
arr1

In [ ]:
arr1.dtype

In [ ]:
arr1.ndim

In [ ]:
arr1.shape

In [ ]:
arr1.size

In [ ]:
arr1.itemsize

In [ ]:
arr1.nbytes

In [47]:
arr1.dtype

dtype('int32')

In [48]:
arr1 = arr1.astype(np.int8)

In [49]:
arr1.dtype

dtype('int8')

In [50]:
arr1[0] = 256

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_33400\2056697916.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr1[0] = 256


In [52]:
arr1 =arr1.astype(np.int16)

In [53]:
arr1[0] = 256

In [54]:
arr1

array([256,   2,   3,   4,   5,   6], dtype=int16)

In [55]:
arr1 = arr1.astype(str)

In [56]:
arr1

array(['256', '2', '3', '4', '5', '6'], dtype='<U6')

In [59]:
np.resize(arr1,(4,4))

array([['256', '2', '3', '4'],
       ['5', '6', '256', '2'],
       ['3', '4', '5', '6'],
       ['256', '2', '3', '4']], dtype='<U6')

In [64]:
arr1.resize(10,refcheck=False)

In [65]:
arr1

array(['256', '2', '3', '4', '', '', '', '', '', ''], dtype='<U6')

In [67]:
arr1 = np.array([1,2,3,4,5,6])

In [68]:
arr1.resize(10,refcheck=False)

In [69]:
arr1

array([1, 2, 3, 4, 5, 6, 0, 0, 0, 0])

In [72]:
arr1.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [0, 0],
       [0, 0]])

In [ ]:
arr1[0] = 255

In [ ]:
arr2 = np.array((1,6,5,5))

In [ ]:
print(arr2)

In [ ]:
print(type(arr1))

In [ ]:
x = {456,123,789}

In [ ]:
arr3 = np.array(x)

In [ ]:
print(arr3)

In [75]:
type(arr1)

numpy.ndarray

In [ ]:
type(x)

In [ ]:
type(arr3)

# Attribute

In [ ]:
arr1.size

In [ ]:
arr1.shape

In [ ]:
arr1.dtype

In [ ]:
arr1

In [ ]:
arr1.ndim

In [ ]:
arr1.itemsize

In [ ]:
arr1.nbytes

# Array Creation

In [ ]:
arr4 = np.arange(1,1000,2) 

In [ ]:
print(arr4)

In [ ]:
arr5 = np.linspace(1,10,500) #linear spaced item

In [ ]:
print(arr5)

In [ ]:
arr5[1] - arr5[0]

In [ ]:
arr5[2] - arr5[1]

In [ ]:
arr5 = np.linspace(1,10,500,endpoint=False) #linear spaced item

In [ ]:
print(arr5)

In [ ]:
matrix_list = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
type(matrix_list)

In [ ]:
matrix = np.array(matrix_list)

In [ ]:
matrix

In [ ]:
type(matrix)

In [ ]:
matrix.size

In [ ]:
matrix.shape

# indexing

In [ ]:
arr2

In [ ]:
arr2[2]

In [ ]:
matrix

In [ ]:
matrix[1,2]

In [ ]:
matrix[1,1]

In [ ]:
matrix[2,2]

In [ ]:
matrix[-2,-2]

In [ ]:
matrix[2,-2]

# Slicing

In [ ]:
matrix

In [ ]:
matrix[1,:]

In [ ]:
matrix[1,0:2]

In [ ]:
matrix[1,0::2]

In [ ]:
matrix

In [ ]:
matrix[0,0]

In [ ]:
matrix[0,-3]

In [ ]:
matrix[0::2,0]

In [ ]:
x = np.arange(12)

In [ ]:
x.ndim

In [ ]:
X = x.reshape((3,2,2))

In [ ]:
X

In [ ]:
X[0,0,0]

In [ ]:
X[0,0,1]

In [ ]:
X[1,0,0]

In [ ]:
X.shape

In [ ]:
X.size

In [ ]:
X

In [ ]:
X[1,1,1] # (last:column,secondlast:row,thirdlast:page)

In [ ]:
X[0,1,0]

In [ ]:
X

In [ ]:
X[0,1,:]

In [ ]:
y = np.arange(36)

In [ ]:
y = y.reshape(3,3,4)

In [ ]:
y

In [ ]:
y[1,1,0::2]

In [ ]:
y = y.astype("float")

In [ ]:
y.dtype

In [ ]:
y

In [ ]:
iter_a = range(10)

In [ ]:
np.fromiter(iter_a,dtype = "int")

In [ ]:
str1 = "shubham"
str1 = iter(str1)

In [ ]:
np.zeros(3)

In [ ]:
np.ones(10)

In [ ]:
np.ones(10).size

In [ ]:
np.empty((2,2))

In [ ]:
np.zeros((3,3))

In [ ]:
z = np.ones((5,6))

In [ ]:
z[1,3] = 56

In [ ]:
z

In [ ]:
np.full(3,2)

In [ ]:
np.full((3,3),5)

In [ ]:
np.ones((3,3))*5

In [ ]:
np.eye(3,1)

In [ ]:
np.eye(3,k = -1)

In [ ]:
np.eye(3)

In [ ]:
np.eye?

In [ ]:
np.identity(3)

In [ ]:
np.identity(5)

In [ ]:
np.identity(6)

In [ ]:
np.identity?

In [ ]:
np.diag?

In [ ]:
a = np.arange(3,7).reshape(2,2)

In [ ]:
a

In [ ]:
b = np.diag(a)

In [ ]:
b

In [ ]:
np.diag(a,k = -1)

In [ ]:
np.diag(b)

In [ ]:
np.random.rand(100)

In [ ]:
np.random.rand?

In [ ]:
np.random.rand(3,3)

In [ ]:
np.random.rand(3,5,2)

In [ ]:
c = np.random.randn(10000) # normally distributed

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(c)

In [ ]:
np.random.randint(2,10, size=(2,3))

In [ ]:
np.random.seed(5)
otp = np.random.randint(10,size = 4)

In [ ]:
otp

In [ ]:
np.random.seed(5)

In [ ]:
np.random.random(10) # 0 to 1 # probability

In [ ]:
list1 = [1,40,56]

In [ ]:
np.random.choice(list1)

In [ ]:
com = 0
player = 0

In [ ]:
list_choice = ["rock","paper","scissor"]

In [ ]:
com_choice = np.random.choice(list_choice)

In [ ]:
player_choice = list_choice[int(input(f"{list(enumerate(list_choice))}"))]

In [ ]:
if com_choice == player_choice:
    print("tie")
elif com_choice == "rock" and player_choice == "sciser":
    com += 1
    print("com win")
else:
    player += 1
    print("player win")

In [ ]:
com

In [ ]:
player

In [ ]:
np.random.seed(0) # lock or reproduce results
print("Reproducible random:", np.random.choice(list_choice))

In [ ]:
print("Reproducible random:", np.random.choice(list_choice))

In [ ]:
 np.random.shuffle(list_choice)

In [ ]:
list_choice = np.array(list_choice)

In [ ]:
list_choice.T

In [ ]:
t1 = np.arange(12).reshape(4,3)

In [ ]:
t1

In [ ]:
t1.T

In [ ]:
t1.sum(axis=0)

In [ ]:
t1.sum(axis=1)

In [ ]:
t1.sum()