In [1]:
import numpy as np

In [2]:
arr_1 = np.array((1,2,3,4,5,6)) # tuple

In [3]:
arr_1

array([1, 2, 3, 4, 5, 6])

In [4]:
print(arr_1)

[1 2 3 4 5 6]


In [5]:
arr_2 = np.array([1,2,3,4,5,6]) # list

In [6]:
arr_2

array([1, 2, 3, 4, 5, 6])

In [7]:
print(arr_2)

[1 2 3 4 5 6]


In [8]:
arr_3=np.array({1,2,3})

In [9]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [10]:
np.arange(11,900,2)

array([ 11,  13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,
        37,  39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,
        63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,
        89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113,
       115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
       141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165,
       167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191,
       193, 195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217,
       219, 221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243,
       245, 247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269,
       271, 273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295,
       297, 299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321,
       323, 325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347,
       349, 351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 37

In [11]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(1,10,50) # min,max,num of value

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [14]:
1.18367347-  1.36734694

-0.18367347

In [15]:
4.12244898- 4.30612245

-0.18367347000000045

In [16]:
print(np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],dtype=float))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
dim_5=np.zeros((3,2,3,3,3))

In [21]:
dim_5[0,1,2,2,2]=5.0

In [22]:
dim_5

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 5.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
  

In [23]:
dim_5[1,1,2,2,2]=6.0

In [24]:
dim_5

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 5.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 6.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
  

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.empty((2, 2))

array([[0.00000000e+000, 1.17362369e-311],
       [1.17362369e-311, 1.17362369e-311]])

In [28]:
arr_1

array([1, 2, 3, 4, 5, 6])

In [29]:
arr_1.size

6

In [30]:
arr_1.shape

(6,)

In [31]:
arr_1.dtype

dtype('int32')

In [32]:
arr_1.ndim

1

In [33]:
arr_1

array([1, 2, 3, 4, 5, 6])

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape: {arr.shape}")      # (2, 3)
print(f"Dtype: {arr.dtype}")      # int64
print(f"Size: {arr.size}")        # 6
print(f"Ndim: {arr.ndim}")

Shape: (2, 3)
Dtype: int32
Size: 6
Ndim: 2


In [35]:
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)
arr_float = arr_int.astype(float)
print(arr_float)      # Output: [1. 2. 3.]
print(arr_float.dtype)

int32
[1. 2. 3.]
float64


In [36]:
arr_float = np.array([1.9, 2.1, 3.7])
arr_int = arr_float.astype(int)
print(arr_int)

[1 2 3]


In [37]:
arr = np.array([1, 2, 3])
arr_str = arr.astype(str)
print(arr_str)
print(arr)


['1' '2' '3']
[1 2 3]


In [38]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)

float32


In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result) 

[5 7 9]


In [40]:
result = arr2 - arr1
print(result)

[3 3 3]


In [41]:
result = arr1 * arr2
print(result)

[ 4 10 18]


In [42]:
result = arr2 / arr1
print(result) 

[4.  2.5 2. ]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
scalar = 2
result = arr * scalar
print(result)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [44]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])      # Output: 10 (first element)
print(arr[-1])     # Output: 50 (last element)
print(arr[2])

10
50
30


In [45]:
arr[1:3]

array([20, 30])

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [47]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
arr[1,1]

5

In [49]:
arr[1,:]

array([4, 5, 6])

In [50]:
arr[1,0]

4

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr[1,0:2]

array([4, 5])

In [53]:
arr[-3,::2]

array([1, 3])

In [54]:
arr_3=np.ones((3,3,3))

In [55]:
print(arr_3)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [56]:
arr_3[1,1,1]=5.0

In [57]:
arr_3[1,1,1]

5.0

In [58]:
print(arr_3)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 5. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [59]:
arr_3[1,2,-2]=-3.0

In [60]:
print(arr_3)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  5.  1.]
  [ 1. -3.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [61]:
arr_3[1,1:,1]

array([ 5., -3.])

In [62]:
arr_3[1,:2,:2]

array([[1., 1.],
       [1., 5.]])

In [63]:
print(arr_3)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  5.  1.]
  [ 1. -3.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [64]:
arr_3[1:,1:,0:]

array([[[ 1.,  5.,  1.],
        [ 1., -3.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [65]:
a = np.arange(24)

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
a = a.reshape(4,2,3)

In [68]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [69]:
a.ndim

3

In [70]:
a.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
a.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [72]:
a.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [73]:
a.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [74]:
a[2,0,1]

13

In [75]:
a[2,0,:]

array([12, 13, 14])

In [76]:
a[2,0,1:]

array([13, 14])

In [77]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [78]:
a.reshape(8,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [79]:
a.reshape(8,5)

ValueError: cannot reshape array of size 24 into shape (8,5)

In [80]:
a.reshape(4,5)

ValueError: cannot reshape array of size 24 into shape (4,5)

In [81]:
np.array([1,2],ndmin=5).shape

(1, 1, 1, 1, 2)

In [82]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [83]:
b=a.copy()

In [84]:
b[0,1,1]=5

In [85]:
b

array([[[ 0,  1,  2],
        [ 3,  5,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [86]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [87]:
# view
c=b.view()

In [88]:
c[0,1,1]=6

In [89]:
c

array([[[ 0,  1,  2],
        [ 3,  6,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [90]:
b

array([[[ 0,  1,  2],
        [ 3,  6,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [91]:
d= b[0,:,:]

In [92]:
d

array([[0, 1, 2],
       [3, 6, 5]])

In [93]:
d[0,0]=5

In [94]:
d

array([[5, 1, 2],
       [3, 6, 5]])

In [95]:
b

array([[[ 5,  1,  2],
        [ 3,  6,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [96]:
np.full?

Signature: np.full(shape, fill_value, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarra

In [97]:
full = np.full((2, 2), 7)
full

array([[7, 7],
       [7, 7]])

In [98]:
full = np.full((2, 2,2), 5)
full

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [99]:
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [100]:
eye = np.eye(3,3,-1)
eye

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [101]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
eye = np.eye((4))
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
np.identity?

Signature: np.identity(n, dtype=None, *, like=None)
Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

Parameters
----------
n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

Examples
--------
>>> np.identity(3)
array([[1.,  0.,  0.],
       [0.,  1.,  0.],
       [0.,  0.,  1.]])
File:      c:\users\hp\appdata\local\programs\python\python312\lib\si

In [105]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [107]:
np.random.randint(5,10,(3,2))

array([[9, 6],
       [6, 6],
       [7, 8]])

In [108]:
np.random.randint(5,10,5)

array([7, 8, 7, 6, 7])

In [109]:
arr=np.array([1,2,5,3,4])

In [116]:
np.random.choice(arr)

5

In [117]:
np.random.choice?

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the `~numpy.random.Generator.choice`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement. Default is True,
    meaning that a value of ``a`` can be selected multiple times.
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given, the sample assumes a unif

In [118]:
arr

array([1, 2, 5, 3, 4])

In [120]:
np.random.choice(arr,(2,3))

array([[3, 4, 4],
       [5, 2, 3]])

In [121]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [126]:
np.random.randn(5)

array([-1.07675592,  0.48121733, -0.87336187, -0.05823939,  1.01160372])

In [128]:
np.random.randn(4,3)

array([[ 0.30774645,  0.00531185, -1.56056212],
       [ 0.11411105, -0.34519245,  0.10877405],
       [ 0.48942365, -0.39195587, -1.05369214],
       [ 0.07217596,  0.06756644,  0.48198139]])

In [129]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method

In [141]:
np.random.randint(5)

3

In [142]:
np.random.seed(2)
np.random.randint(5)

0

In [143]:
np.random.seed?

Docstring:
seed(seed=None)

Reseed the singleton RandomState instance.

Notes
-----
This is a convenience, legacy function that exists to support
older code that uses the singleton RandomState. Best practice
is to use a dedicated ``Generator`` instance rather than
the random variate generation methods exposed directly in
the random module.

See Also
--------
numpy.random.Generator
Type:      builtin_function_or_method

In [144]:
arr

array([1, 2, 5, 3, 4])

In [149]:
np.random.shuffle(arr)

In [150]:
arr

array([4, 1, 3, 2, 5])