In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)  # Output: [5 7 9]

[5 7 9]


In [4]:
result = arr2 - arr1
print(result)

[3 3 3]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2
result = arr * scalar
print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [8]:
import numpy as np
import time

# Create large dataset
size = 1_000_000
start = time.time()
# Python list
python_list = list(range(size))
list_time = time.time() - start
print(list_time)
# NumPy array

num_start = time.time()
numpy_array = np.arange(size)
arr_time = time.time() - num_start
print(arr_time)
print(f"Size: {size} elements")
print("=" * 50)

0.058328866958618164
0.005850315093994141
Size: 1000000 elements


In [9]:
a1 = np.arange(3).reshape((1,3))

In [10]:
a2 = np.arange(3).reshape((3,1))

In [11]:
a1+a2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])