In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [3]:
arr1 = np.array([1,2,3,4,5,6])

In [4]:
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
print(arr1)

[1 2 3 4 5 6]


In [6]:
arr2 = np.array((1,6,5,5))

In [7]:
print(arr2)

[1 6 5 5]


In [8]:
type(arr1)

numpy.ndarray

In [9]:
x = [456,123,789]

In [10]:
arr3 = np.array(x)

In [11]:
print(arr3)

[456 123 789]


In [12]:
type(x)

list

In [13]:
type(arr3)

numpy.ndarray

# Attribute

In [14]:
arr1.size

6

In [15]:
arr1.shape

(6,)

In [17]:
arr1.dtype

dtype('int64')

In [18]:
arr1

array([1, 2, 3, 4, 5, 6])

In [19]:
arr1.ndim

1

In [20]:
arr1.itemsize

8

In [23]:
arr4 = np.arange(1,1000,2) 

In [24]:
print(arr4)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

In [29]:
arr5 = np.linspace(1,10,500) #linear spaced item

In [30]:
print(arr5)

[ 1.          1.01803607  1.03607214  1.05410822  1.07214429  1.09018036
  1.10821643  1.12625251  1.14428858  1.16232465  1.18036072  1.19839679
  1.21643287  1.23446894  1.25250501  1.27054108  1.28857715  1.30661323
  1.3246493   1.34268537  1.36072144  1.37875752  1.39679359  1.41482966
  1.43286573  1.4509018   1.46893788  1.48697395  1.50501002  1.52304609
  1.54108216  1.55911824  1.57715431  1.59519038  1.61322645  1.63126253
  1.6492986   1.66733467  1.68537074  1.70340681  1.72144289  1.73947896
  1.75751503  1.7755511   1.79358717  1.81162325  1.82965932  1.84769539
  1.86573146  1.88376754  1.90180361  1.91983968  1.93787575  1.95591182
  1.9739479   1.99198397  2.01002004  2.02805611  2.04609218  2.06412826
  2.08216433  2.1002004   2.11823647  2.13627255  2.15430862  2.17234469
  2.19038076  2.20841683  2.22645291  2.24448898  2.26252505  2.28056112
  2.29859719  2.31663327  2.33466934  2.35270541  2.37074148  2.38877756
  2.40681363  2.4248497   2.44288577  2.46092184  2

In [31]:
arr5[1] - arr5[0]

np.float64(0.018036072144288484)

In [32]:
arr5[2] - arr5[1]

np.float64(0.018036072144288706)

In [33]:
matrix_list = [[1,2,3],[4,5,6],[7,8,9]]

In [34]:
type(matrix_list)

list

In [35]:
matrix = np.array(matrix_list)

In [36]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
type(matrix)

numpy.ndarray

In [38]:
matrix.size

9

In [39]:
matrix.shape

(3, 3)

# indexing

In [40]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
matrix[1,1]

np.int64(5)

In [42]:
matrix[2,2]

np.int64(9)

In [43]:
matrix[-2,-2]

np.int64(5)

In [44]:
matrix[2,-2]

np.int64(8)

# Slicing

In [45]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
matrix[1,:]

array([4, 5, 6])

In [47]:
matrix[1,0:2]

array([4, 5])

In [50]:
matrix[1,0::2]

array([4, 6])

In [51]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
matrix[0,0]

np.int64(1)

In [53]:
matrix[0,-3]

np.int64(1)

In [55]:
matrix[0::2,0]

array([1, 7])

In [57]:
x = np.arange(8)

In [59]:
X = x.reshape((2,2,2))

In [60]:
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
X[0,0,0]

np.int64(0)

In [62]:
X[0,0,1]

np.int64(1)

In [63]:
X[1,0,0]

np.int64(4)

In [64]:
X.shape

(2, 2, 2)

In [65]:
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
X[1,1,1] # (last:column,secondlast:row,thirdlast:page)

np.int64(7)

In [68]:
X[0,1,0]

np.int64(2)

In [69]:
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
X[0,1,:]

array([2, 3])

In [77]:
y = np.arange(36)

In [79]:
y = y.reshape((3,3,4))

In [ ]:
16,18

In [80]:
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [83]:
y[1,1,0:3:2]

array([16, 18])

In [85]:
y = y.astype("float")

In [86]:
y.dtype

dtype('float64')