In [1]:
import numpy as np

In [2]:
arr_1 = np.array((1,2,3,4,5,6)) # tuple

In [3]:
arr_1

array([1, 2, 3, 4, 5, 6])

In [4]:
print(arr_1)

[1 2 3 4 5 6]


In [5]:
arr_2 = np.array([1,2,3,4,5,6]) # list

In [6]:
arr_2

array([1, 2, 3, 4, 5, 6])

In [7]:
print(arr_2)

[1 2 3 4 5 6]


In [8]:
arr_3=np.array({1,2,3})

In [9]:
arr_3

array({1, 2, 3}, dtype=object)

In [10]:
print(arr_3)

{1, 2, 3}


In [11]:
type(arr_3)

numpy.ndarray

In [12]:
arr_1.dtype

dtype('int32')

In [13]:
arr_1.ndim

1

In [14]:
arr_1.shape

(6,)

In [15]:
arr_1*2

array([ 2,  4,  6,  8, 10, 12])

In [18]:
arr_1[-1]

6

In [19]:
arr_1[-1] = 56

In [20]:
arr_1

array([ 1,  2,  3,  4,  5, 56])

In [39]:
arr_1[0] = 127

In [40]:
arr_1

array([127,   2,   3,   4,   5, 127], dtype=int8)

In [42]:
arr_1 = arr_1.astype(np.uint8)

In [43]:
arr_1.dtype

dtype('uint8')

In [47]:
arr_1[0] = 256

C:\Users\SHUBHAM\AppData\Local\Temp\ipykernel_3520\2249638475.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr_1[0] = 256


In [48]:
arr_1

array([  0,   2,   3,   4,   5, 127], dtype=uint8)

In [31]:
arr_1 = arr_1.astype(np.int8)

In [49]:
arr_1[0:3]

array([0, 2, 3], dtype=uint8)

In [51]:
arr_1 = arr_1.reshape((3,2))

In [52]:
arr_1

array([[  0,   2],
       [  3,   4],
       [  5, 127]], dtype=uint8)

In [53]:
arr_1[2,1]

127

In [54]:
arr_1[-1,:]

array([  5, 127], dtype=uint8)

In [56]:
arr_4 = np.arange(12).reshape(3,2,2)

In [60]:
arr_4

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [61]:
arr_4[2,1,1]

11

In [63]:
arr_4[2,1,:]

array([10, 11])

In [59]:
arr_4.shape

(3, 2, 2)

In [65]:
arr_5 = arr_4.copy()

In [66]:
arr_5

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [67]:
arr_4+arr_5

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [72]:
arr_1 + arr_5

array([[[  0,   1],
        [  4,   5]],

       [[  7,   8],
        [ 10,  11]],

       [[ 13,  14],
        [137, 138]]])

In [71]:
arr_1 = arr_1[:,:,np.newaxis]

In [25]:
np.array([1,2,3,4,5,0],dtype=bool,ndmin = 10)

array([[[[[[[[[[ True,  True,  True,  True,  True, False]]]]]]]]]])

In [21]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [73]:
np.arange(11,900,2)

array([ 11,  13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,
        37,  39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,
        63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,
        89,  91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113,
       115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139,
       141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165,
       167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191,
       193, 195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217,
       219, 221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243,
       245, 247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269,
       271, 273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295,
       297, 299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321,
       323, 325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347,
       349, 351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 37

In [74]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002BB7F3700E0>
File:            c:\users\shubham\appdata\local\programs\python\python312\lib\site-packages\numpy\core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.

In [81]:
np.linspace(1,10,50,endpoint = False) # min,max,num of value

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

In [77]:
1.18367347-1

0.18367347

In [78]:
1.18367347-  1.36734694

-0.18367347

In [ ]:
4.12244898- 4.30612245

In [ ]:
print(np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],dtype=float))

In [82]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
dim_5=np.zeros((3,2,3,3,3))

In [ ]:
dim_5[0,1,2,2,2]=5.0

In [ ]:
dim_5

In [ ]:
dim_5[1,1,2,2,2]=6.0

In [ ]:
dim_5

In [85]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [86]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.empty((2, 2))

array([[0.00000000e+000, 1.48419627e-311],
       [1.48419626e-311, 1.48419626e-311]])

In [ ]:
arr_1

In [ ]:
arr_1.size

In [ ]:
arr_1.shape

In [ ]:
arr_1.dtype

In [ ]:
arr_1.ndim

In [ ]:
arr_1

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape: {arr.shape}")      # (2, 3)
print(f"Dtype: {arr.dtype}")      # int64
print(f"Size: {arr.size}")        # 6
print(f"Ndim: {arr.ndim}")

In [ ]:
arr_int = np.array([1, 2, 3])
print(arr_int.dtype)
arr_float = arr_int.astype(float)
print(arr_float)      # Output: [1. 2. 3.]
print(arr_float.dtype)

In [ ]:
arr_float = np.array([1.9, 2.1, 3.7])
arr_int = arr_float.astype(int)
print(arr_int)

In [ ]:
arr = np.array([1, 2, 3])
arr_str = arr.astype(str)
print(arr_str)
print(arr)


In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result) 

In [ ]:
result = arr2 - arr1
print(result)

In [ ]:
result = arr1 * arr2
print(result)

In [ ]:
result = arr2 / arr1
print(result) 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
scalar = 2
result = arr * scalar
print(result)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])      # Output: 10 (first element)
print(arr[-1])     # Output: 50 (last element)
print(arr[2])

In [ ]:
arr[1:3]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
print(arr)

In [ ]:
arr[1,1]

In [ ]:
arr[1,:]

In [ ]:
arr[1,0]

In [ ]:
arr

In [ ]:
arr[1,0:2]

In [ ]:
arr[-3,::2]

In [ ]:
arr_3=np.ones((3,3,3))

In [ ]:
print(arr_3)

In [ ]:
arr_3[1,1,1]=5.0

In [ ]:
arr_3[1,1,1]

In [ ]:
print(arr_3)

In [ ]:
arr_3[1,2,-2]=-3.0

In [ ]:
print(arr_3)

In [ ]:
arr_3[1,1:,1]

In [ ]:
arr_3[1,:2,:2]

In [ ]:
print(arr_3)

In [ ]:
arr_3[1:,1:,0:]

In [ ]:
a = np.arange(24)

In [ ]:
a

In [ ]:
a = a.reshape(4,2,3)

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
a.reshape(6,4)

In [ ]:
a.reshape(12,2)

In [ ]:
a.reshape(8,3)

In [ ]:
a.reshape(24,1)

In [ ]:
a[2,0,1]

In [ ]:
a[2,0,:]

In [ ]:
a[2,0,1:]

In [ ]:
a.reshape(3,-1)

In [ ]:
a.reshape(8,-1)

In [ ]:
a.reshape(8,5)

In [ ]:
a.reshape(4,5)

In [ ]:
np.array([1,2],ndmin=5).shape

In [ ]:
a

In [ ]:
b=a.copy()

In [ ]:
b[0,1,1]=5

In [ ]:
b

In [ ]:
a

In [ ]:
# view
c=b.view()

In [ ]:
c[0,1,1]=6

In [ ]:
c

In [ ]:
b

In [ ]:
d= b[0,:,:]

In [ ]:
d

In [ ]:
d[0,0]=5

In [ ]:
d

In [ ]:
b

In [ ]:
np.full?

In [ ]:
full = np.full((2, 2), 7)
full

In [ ]:
full = np.full((2, 2,2), 5)
full

In [ ]:
np.eye?

In [ ]:
eye = np.eye(3,3,-1)
eye

In [ ]:
eye = np.eye(3)
eye

In [ ]:
eye = np.eye((4))
eye

In [ ]:
identity = np.identity(3)
identity

In [ ]:
np.identity?

In [ ]:
identity = np.identity(3)
identity

In [ ]:
np.random.randint?

In [ ]:
np.random.randint(5,10,(3,2))

In [ ]:
np.random.randint(5,10,5)

In [ ]:
arr=np.array([1,2,5,3,4])

In [ ]:
np.random.choice(arr)

In [ ]:
np.random.choice?

In [ ]:
arr

In [ ]:
np.random.choice(arr,(2,3))

In [ ]:
np.random.randn?

In [ ]:
np.random.randn(5)

In [ ]:
np.random.randn(4,3)

In [ ]:
np.random.rand?

In [ ]:
np.random.randint(5)

In [ ]:
np.random.seed(2)
np.random.randint(5)

In [ ]:
np.random.seed?

In [ ]:
arr

In [ ]:
np.random.shuffle(arr)

In [ ]:
arr

In [90]:
arr_2

array([1, 2, 3, 4, 5, 6])

In [91]:
arr_5 = arr_2.copy()

In [92]:
arr_2

array([1, 2, 3, 4, 5, 6])

In [93]:
arr_5

array([1, 2, 3, 4, 5, 6])

In [94]:
arr_5[0] =25

In [95]:
arr_5

array([25,  2,  3,  4,  5,  6])

In [96]:
arr_2

array([1, 2, 3, 4, 5, 6])

In [97]:
arr_6=arr_2.view()

In [98]:
arr_6

array([1, 2, 3, 4, 5, 6])

In [99]:
arr_2[0]=25

In [100]:
arr_2

array([25,  2,  3,  4,  5,  6])

In [101]:
arr_6

array([25,  2,  3,  4,  5,  6])

In [102]:
arr_6[0]=1

In [103]:
arr_6

array([1, 2, 3, 4, 5, 6])

In [104]:
arr_2

array([1, 2, 3, 4, 5, 6])

In [110]:
arr_7=arr_2[3:]

In [111]:
arr_7

array([4, 5, 6])

In [112]:
arr_7[0]=50

In [113]:
arr_7

array([50,  5,  6])

In [114]:
arr_2

array([50,  2,  3, 50,  5,  6])